Remove reference to devstack-gate
devstack-gate was deprecated in xena and is being retired now[1].

[1] https://review.opendev.org/c/openstack/governance/+/919629

Backport note:
* Bump pylint to resolve the following error in pep8 job.
   AttributeError: module 'astroid' has no attribute 'TryExcept'
* Switch neutron-tempest-plugin job to the one for stable branches

Change-Id: I762503b4c6f05b79f46d36ca42cb588e28dfc6d1
(cherry picked from commit d0fd419596b2be1f750c98cb4b6102e1c6d834e6)
(cherry picked from commit cf4497fecddf4dd07dfe850278f6720c629a6319)