Pin isort to 4.3.21
This patch fixes multiple issues to unblock gate:

1. With new isort releases (5.X.X) pylint started to fail, with error:

     AttributeError: module 'isort' has no attribute 'SortImports'

   This patch pin isort to 4.3.21, the last version before 5.0.0.

2. Original commit had fixes for lower-constraints, dropped in this
   branch, see below

3. Functional job fails, because during tox run the latest released
   neutron is installed and it requires mock to be installed. This
   patch adds mock to functional test requirements. Note: this needs
   to be deleted as soon as new neutron will be released as on
   development branch neutron does not depend on mock anymore.

4. Another fix had to squashed into this patch as functional job
   neutron-vpnaas-functional-sswan fails with missing 'pip' command
   (called from configure_for_vpn_func_testing.sh) without this fix:

   Fix functional gate failure

   Using command pip3 for python3-pip package.

   Change-Id: I9f0c7ed7cf8baaa20e382e11e2276498d1c572fe
   (cherry picked from commit d4ef9c04ff03840665f5a47a421ae842db551264)

Additional fixes for stable/train:

1. Drop lower-constraints
   They were fixed in ussuri but need additional changes in train, drop
   them completely for this branch as it was done already in many other
   stable branches

2. Add ensure-tox role for functional job
   Job was converted in newer branches but fails in train with
   tox: command not found

3. Drop psutil from functional requirements as done in other branches

4. Use the 'all' tox env instead of 'all-plugin'

5. Move neutron-vpnaas-tempest-libreswan-centos to experimental

Conflicts:
	test-requirements.txt

Change-Id: Ibc4cd7f8a055457b288ef101893c252cf0464a28
(cherry picked from commit 2b293a1bfae6cefe17efa820e41ef698663749f2)
(cherry picked from commit 180fc9dcbc7debe4a3972a3d2877645a24f27a61)