Pin isort to 4.3.21
This patch fixes multiple issues to unblock gate:

1. With new isort releases (5.X.X) pylint started to fail, with error:

     AttributeError: module 'isort' has no attribute 'SortImports'

   This patch pin isort to 4.3.21, the last version before 5.0.0.

2. lower-constraints of appdirs and pytz need to be updated as
   currently lower-constraints job fails.

   Since patch Ia012a8e116a276a6674f86366c803e0e2d8ff704 modified the
   NEUTRON_PATH variable the functional test fails with:

   [..]neutron/tools/configure_for_func_testing.sh: line 113: /home/zuul/src/opendev.org/openstack/neutron-vpnaas/devstack/lib/ovs: No such file or directory

3. Functional job fails, because during tox run the latest released
   neutron is installed and it requires mock to be installed. This
   patch adds mock to functional test requirements. Note: this needs
   to be deleted as soon as new neutron will be released as on
   development branch neutron does not depend on mock anymore.

Change-Id: Ibc4cd7f8a055457b288ef101893c252cf0464a28